services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Europe/Rome
      - POSTGRES_DB=atleti_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=cr00586

  web:
    build: .
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "127.0.0.1:8001:8000"
    shm_size: '2gb'
    environment:
      - TZ=Europe/Rome
      - DATABASE_URL=postgres://admin:atleti_pass@db:5432/atleti_db
    depends_on:
      - db

  scheduler:
    build: .
    env_file:
      - .env
    command: python manage.py run_scheduler
    volumes:
      - .:/code
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    shm_size: '2gb'
    environment:
      - TZ=Europe/Rome
    depends_on:
      - db

volumes:
  postgres_data:
