services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=atleti_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=cr00586

  web:
    build: .
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:8000:8000"
    shm_size: '2gb'
    environment:
      - DATABASE_URL=postgres://admin:atleti_pass@db:5432/atleti_db
    depends_on:
      - db

  scheduler:
    build: .
    env_file:
      - .env
    command: python manage.py run_scheduler
    volumes:
      - .:/code
    shm_size: '2gb'
    depends_on:
      - db

volumes:
  postgres_data:
